apiVersion: apps/v1
kind: Deployment
metadata:
  name: gophie-web
  labels:
    app: gophie-web
  namespace: gophie 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gophie-web
  template:
    metadata:
      labels:
        app: gophie-web
    spec:
      containers:
      - name: gophie-web 
        image: ghcr.io/go-phie/gophie-web:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000



---
apiVersion: v1
kind: Service
metadata:
  name: gophie-web-service 
  namespace: gophie
spec:
  type: ClusterIP
  selector:
    app: gophie-web 
  ports:
  - port: 80 
    targetPort: 3000
