---
- name: Get Google Key
  become: yes
  apt_key:
    url: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
    state: present

- name: Add Google Repository
  become: yes
  command: sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'

- name: Update Apt
  become: yes
  apt: update_cache=yes

- name: Install Google-Chrome
  become: yes
  apt:
    state: latest
    pkg: ['google-chrome-stable']
