apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocena
spec:
  selector:
    matchLabels:
      app: ocena
  template:
    metadata:
      labels:
        app: ocena
    spec:
      containers:
      - name: ocena
        image: bethelm/bisohns:ocena
        envFrom:
        - secretRef:
            name: ocena-secret
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: ocena-service
spec:
  type: ClusterIP 
  selector:
    app: ocena
  ports:
  - port: 80
    targetPort: 8000

