# Chart repositories used from within this state file
# to use repositories other than the official repository or one backend by chartmuseum.
repositories:
- name: ingress-nginx
  url:  https://kubernetes.github.io/ingress-nginx
- name: jetstack
  url: https://charts.jetstack.io

releases:
  - name: ingress-nginx
    namespace: ingress-nginx
    createNamespace: true
    chart: ingress-nginx/ingress-nginx
    version: 4.6.0
    values:
      - controller:
          ingressClassResource:
            default: true

  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: 1.11.1
    values:
    - installCRDs: true


