apiVersion: apps/v1
kind: Deployment
metadata:
  name: gophie
  labels:
    app: gophie 
  namespace: gophie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gophie
  template:
    metadata:
      labels:
        app: gophie
    spec:
      containers:
      - name: gophie 
        image: bethelm/bisohns:gophieV1
        envFrom:
        - secretRef:
            name: gophie-secret
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000



---
apiVersion: v1
kind: Service
metadata:
  name: gophie-service 
  namespace: gophie
spec:
  type: ClusterIP
  selector:
    app: gophie 
  ports:
  - port: 80 
    targetPort: 3000