---
- hosts: all
  become: yes

  vars:
    mythra_web_path: "/home/gcp/mythra"
    mythra_web_port: 9000

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

    - name: Install packages
      apt:
        state: present
        pkg: [ 'libncurses5', 'libncursesw5-dev', 'libssl-dev', 'pkg-config', 'git', 'unzip', 'lsof']

  tasks:
    - name: Install ChromeDriver
      include_role:
        name: chromedriver

    - name: Install Headless Chrome
      include_role:
        name: chrome


    - name: Clone Master Mythra Web Repo.
      become: no
      git:
        dest: "{{ mythra_web_path }}"
        repo: https://github.com/deven96/mythra.git
        force: yes
        
    - name: Get latest tag
      shell:
        chdir: "{{ mythra_web_path }}"
        cmd: |
           git tag | tail -n 1
      register: latest_tag

    - name: Show Latest Tag
      debug:
        msg: "{{ latest_tag }}"

    - name: Download latest tag
      get_url: 
        url: "{{ 'https://github.com/deven96/mythra/releases/download/{}/mythra-ubuntu-18.04-{}'.format(latest_tag.stdout, latest_tag.stdout) }}"
        dest: "{{ '{}/mythra'.format(mythra_web_path) }}"
        mode: "0755"
        force: yes

    - name: Kill existing processes
      shell:
        cmd: |
          sudo lsof -ti tcp:{{ mythra_web_port }} | sudo xargs kill -9 > /dev/null 2&>1
          sudo lsof -ti tcp:4444 | sudo xargs kill -9 > /dev/null 2&>1
    
    - name: Start ChromeDriver
      shell:
        cmd: |
          chromedriver --port=4444 --log-level=DEBUG &
      async: 45
      poll: 0

    - name: Start Mythra app
      shell:
        chdir: "{{ mythra_web_path }}"
        cmd: |
          ./mythra api --port "{{ mythra_web_port }}" --verbose debug > /tmp/mythra.log &
      async: 45
      poll: 0

    - name: Install Nginx.
      include_role:
        name: geerlingguy.nginx
      vars:
        nginx_vhosts:
          - listen: "443 ssl http2"
            server_name: "mythra.gophie.cam"
            state: "present"
            template: "{{ nginx_vhost_template }}"
            filename: "mythra.cam.80.conf"
            extra_parameters: |
              ssl_certificate     /etc/letsencrypt/live/mythra.gophie.cam/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/mythra.gophie.cam/privkey.pem;
              ssl_protocols       tlsv1.1 tlsv1.2;
              location / {
                proxy_set_header x-forwarded-for $proxy_add_x_forwarded_for;
                proxy_set_header x-real-ip $remote_addr;
                proxy_set_header host $http_host;

                proxy_http_version 1.1;
                proxy_set_header upgrade $http_upgrade;
                proxy_set_header connection "upgrade";

                proxy_pass "http://localhost:{{ mythra_web_port }}/";
                proxy_redirect off;
                proxy_read_timeout 240s;
              }

          - listen: "80"
            server_name: "mythra.gophie.cam"
            return: "301 https://mythra.gophie.cam$request_uri"
            filename: "mythra.cam.80.conf"
