---
- hosts: all
  become: yes

  vars:
    mythra_web_path: "/home/gcp/mythra"
    mythra_web_port: 9000

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

    - name: Install packages
      apt:
        state: present
        pkg: ['libncursesw5-dev', 'libssl-dev', 'pkg-config', 'git', 'unzip', 'lsof']

  tasks:
    - name: Install ChromeDriver
      include_role:
        name: chromedriver

    - name: Install Headless Chrome
      include_role:
        name: chrome

    - name: Install Rust
      include_role:
        name: rust
      vars:
        rust_version: "1.49.0"
        shell_profiles:
          - .bashrc

    - name: Clone Master Mythra Web Repo.
      become: no
      git:
        depth: 1
        dest: "{{ mythra_web_path }}"
        repo: https://github.com/deven96/mythra.git
        force: yes

    - name: Build Code using Cargo.
      shell:
        chdir: "{{ mythra_web_path }}"
        cmd: |
          /root/.cargo/bin/cargo build

    - name: Start ChromeDriver and app
      shell:
        chdir: "{{ mythra_web_path }}"
        cmd: |
          lsof -ti tcp:"{{ mythra_web_port}}" | xargs kill -9
          lsof -ti tcp:4444 | xargs kill -9
          chromedriver --port=4444 --log-level=DEBUG &
          ./target/debug/mythra api --port "{{ mythra_web_port }}" --verbose debug &

    - name: Install Nginx.
      include_role:
        name: geerlingguy.nginx
      vars:
        nginx_vhosts:
          - listen: "80"
            server_name: "_"
            state: "present"
            return: "301 https://gophie.cam$request_uri"
            template: "{{ nginx_vhost_template }}"
            filename: "mythra.cam.80.conf"
            extra_parameters: |
              location / {
                proxy_set_header x-forwarded-for $proxy_add_x_forwarded_for;
                proxy_set_header x-real-ip $remote_addr;
                proxy_set_header host $http_host;

                proxy_http_version 1.1;
                proxy_pass "http://localhost:{{ mythra_web_port }}/";
                proxy_redirect off;
                proxy_read_timeout 240s;
              }
