---
- name: Update Apt
  become: yes
  apt: update_cache=yes

- name: Install Chromedriver Dependencies
  become: yes
  apt:
    state: latest
    pkg: ['libnss3', 'libgconf-2-4']

- name: Get Chromedriver Latest Version Number
  uri:
    url: "{{ chromedriver_version_url }}"
    return_content: yes
    headers:
      Content-Type: "text/plain"
  register: latest_chromedriver

- name: Download Chromedriver
  become: yes
  unarchive:
    src: "https://chromedriver.storage.googleapis.com/{{ latest_chromedriver.content|trim }}/chromedriver_linux64.zip"
    dest: /usr/local/bin
    remote_src: yes
