apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocena
  namespace: gophie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ocena
  template:
    metadata:
      labels:
        app: ocena
    spec:
      containers:
      - name: ocena
        image: bethelm/bisohns:ocenaV2
        envFrom:
        - secretRef:
            name: ocena-secret
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: ocena-service
  namespace: gophie 
spec:
  type: ClusterIP 
  selector:
    app: ocena
  ports:
  - port: 80
    targetPort: 8000

